# Generated by Django 2.1 on 2018-09-13 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('job_desc', models.CharField(max_length=264)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elpapp.Employer')),
            ],
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elpapp.jobs'),
        ),
    ]
