# Generated by Django 2.1 on 2018-09-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elpapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(default='something@somemail.com', max_length=264, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default='something@somemail.com', max_length=264, unique=True),
        ),
    ]
